"""added email to trans

Revision ID: 52391e547b95
Revises: 
Create Date: 2021-03-09 22:02:18.649336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52391e547b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trans', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trans', 'email')
    # ### end Alembic commands ###
