"""added job queue id to table

Revision ID: e90924c07c01
Revises: 52391e547b95
Create Date: 2021-03-10 01:10:45.899391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90924c07c01'
down_revision = '52391e547b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trans', sa.Column('queueJobId', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trans', 'queueJobId')
    # ### end Alembic commands ###
